{{- include "helm-library.configmap" (list . "power-lines-analysis-service.configmap") -}}
{{- define "power-lines-analysis-service.configmap" -}}
data:
  ConnectionStrings__PowerLinesAnalysisService: {{ quote .Values.container.connectionString }}
  Message__Host: {{ quote .Values.message.host }}
  Message__Port: {{ quote .Values.message.port }}
  Message__Username: {{ quote .Values.message.username }}
  Message__Password: {{ quote .Values.message.password }}
  Message__AnalysisQueue: {{ quote .Values.message.analysisQueue }}
  Message__ResultQueue: {{ quote .Values.message.resultQueue }}
  Message__ResultSubscription: {{ quote .Values.message.resultSubscription }}
  Message__OddsQueue: {{ quote .Values.message.oddsQueue }}
  Message__AnalysisSubscription: {{ quote .Values.message.analysisSubscription }}
  COMPlus_EnableDiagnostics: {{ quote .Values.container.comPlusEnableDiagnostics }}
  ASPNETCORE_ENVIRONMENT: {{ quote .Values.environment }}
{{- end -}}
