{{- include "helm-library.horozontal-pod-autoscaler" (list . "power-lines-analysis-service.horozontal-pod-autoscaler") -}}
{{- define "power-lines-analysis-service.horozontal-pod-autoscaler" -}}
spec:  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.deployment.cpuThreshold }}
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: {{ .Values.deployment.memoryThreshold }}
{{- end -}}
