apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote }}-results
spec:
  scaleTargetRef:
    name: rabbitmq-deployment
  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://{{ .Values.message.username }}:{{ .Values.message.password }}@{{ .Values.message.host }}:{{ .Values.message.port }}/
      queueName: {{ .Values.message.resultSubscription }}
      mode: QueueLength
      value: {{ .Values.deployment.triggerQueueLength }}
      minReplicaCount: {{ .Values.deployment.minReplicas }}
      maxReplicaCount: {{ .Values.deployment.maxReplicas }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote }}-analysis
spec:
  scaleTargetRef:
    name: rabbitmq-deployment
  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://{{ .Values.message.username }}:{{ .Values.message.password }}@{{ .Values.message.host }}:{{ .Values.message.port }}/
      queueName: {{ .Values.message.analysisSubscription }}
      mode: QueueLength
      value: {{ .Values.deployment.triggerQueueLength }}
      minReplicaCount: {{ .Values.deployment.minReplicas }}
      maxReplicaCount: {{ .Values.deployment.maxReplicas }}
