apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.name }}
spec:
  scaleTargetRef:
    name: {{ .Values.name }}
  minReplicaCount: {{ .Values.deployment.minReplicas }}
  maxReplicaCount: {{ .Values.deployment.maxReplicas }}
  triggers:
  - type: rabbitmq
    metadata:
      hostFromEnv: MESSAGE_HOST_STRING
      queueName: {{ .Values.message.resultSubscription }}
      mode: QueueLength
      value: {{ .Values.deployment.triggerQueueLength }}
  - type: rabbitmq
    metadata:
      hostFromEnv: MESSAGE_HOST_STRING
      queueName: {{ .Values.message.analysisSubscription }}
      mode: QueueLength
      value: {{ .Values.deployment.triggerQueueLength }}
