apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.name }}-results
spec:
  scaleTargetRef:
    name: rabbitmq-deployment
  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://{{ .Values.message.username }}:{{ .Values.message.password }}@{{ .Values.message.host }}:{{ .Values.message.port }}/
      queueName: {{ .Values.message.resultSubscription }}
      mode: QueueLength
      value: {{ .Values.deployment.triggerQueueLength | quote }}
      minReplicaCount: {{ .Values.deployment.minReplicas | quote }}
      maxReplicaCount: {{ .Values.deployment.maxReplicas | quote }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.name }}-analysis
spec:
  scaleTargetRef:
    name: rabbitmq-deployment
  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://{{ .Values.message.username }}:{{ .Values.message.password }}@{{ .Values.message.host }}:{{ .Values.message.port }}/
      queueName: {{ .Values.message.analysisSubscription }}
      mode: QueueLength
      value: {{ .Values.deployment.triggerQueueLength | quote }}
      minReplicaCount: {{ .Values.deployment.minReplicas | quote }}
      maxReplicaCount: {{ .Values.deployment.maxReplicas | quote }}
