apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.name }}-results
spec:
  scaleTargetRef:
    deploymentName: {{ .Values.name }}
  triggers:
  - type: rabbitmq
    metadata:
      host: MESSAGE_HOST
      queueName: {{ .Values.message.resultSubscription }}
      mode: QueueLength
      value: {{ .Values.deployment.triggerQueueLength | quote }}
      minReplicaCount: {{ .Values.deployment.minReplicas | quote }}
      maxReplicaCount: {{ .Values.deployment.maxReplicas | quote }}
  - type: rabbitmq
    metadata:
      host: MESSAGE_HOST
      queueName: {{ .Values.message.analysisSubscription }}
      mode: QueueLength
      value: {{ .Values.deployment.triggerQueueLength | quote }}
      minReplicaCount: {{ .Values.deployment.minReplicas | quote }}
      maxReplicaCount: {{ .Values.deployment.maxReplicas | quote }}
