services:
  power-lines-analysis-service:
    build:
      target: development
    depends_on: 
      power-lines-message:
        condition: service_healthy
      power-lines-analysis-service-postgres:
        condition: service_healthy
    ports:
      - "5003:5003"
    environment:
      CONNECTIONSTRINGS__POWERLINESANALYSISSERVICE: "Server=power-lines-analysis-service-postgres;Port=5432;Database=power_lines_analysis;User Id=postgres;Password=postgres;"
      MESSAGE__HOST: power-lines-message
    volumes:
      - ./PowerLinesAnalysisService:/home/dotnet/PowerLinesAnalysisService
    networks:
      - power-lines

  power-lines-message:
    image: rabbitmq:3-management-alpine
    container_name: power-lines-message
    hostname: power-lines-message
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitmq
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - power-lines
    healthcheck:
      test: rabbitmq-diagnostics -q ping --erlang-cookie rabbitmq
      interval: 10s
      retries: 5
      start_period: 1s
      timeout: 10s

  power-lines-analysis-service-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: power_lines_analysis
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6003:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - power-lines
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 1s
      timeout: 10s

volumes:
  postgres_data: {}

networks:
  power-lines:
    driver: bridge
    name: power-lines
