services:
  power-lines-analysis-service:
    build:
      target: development
    depends_on: 
      - power-lines-message
      - power-lines-analysis-service-postgres
    entrypoint: >
      sh -c "
        scripts/wait-for.sh power-lines-message:5672 --
        scripts/wait-for.sh power-lines-analysis-service-postgres:6003 --
        dotnet watch --project ./PowerLinesAnalysisService run"
    ports:
      - "5003:5003"
    environment:
      ConnectionStrings__PowerLinesAnalysisService: "Server=power-lines-analysis-service-postgres;Port=5432;Database=power_lines_analysis;User Id=postgres;Password=postgres;"
      Message__Host: power-lines-message
    volumes:
      - ./PowerLinesAnalysisService:/home/dotnet/PowerLinesAnalysisService
      - ./PowerLinesAnalysisService.Tests:/home/dotnet/PowerLinesAnalysisService.Tests
      - ./scripts:/home/dotnet/scripts
    networks:
      - power-lines

  power-lines-message:
    image: rabbitmq:3-management-alpine
    container_name: power-lines-message
    hostname: power-lines-message
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitmq
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - power-lines

  power-lines-analysis-service-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: power_lines_analysis
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6003:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - power-lines

volumes:
  postgres_data: {}

networks:
  power-lines:
    driver: bridge
    name: power-lines
