version: '3.7'
services:
  power-lines-analysis-service:
    build:
      target: development
    depends_on: 
      - power-lines-message
      - power-lines-analysis-service-postgres
    entrypoint: >
      sh -c "
        scripts/wait-for.sh power-lines-message:5672 --
        scripts/wait-for.sh power-lines-analysis-service-postgres:6001 --
        dotnet watch --project ./PowerLinesAnalysisService run --urls "http://*:5001""
    ports:
      - "5001:5001"
    environment:
      ConnectionStrings__PowerLinesAnalysisService: "Server=power-lines-analysis-service-postgres;Port=5432;Database=power_lines_analysis;User Id=postgres;Password=postgres;"
      Message__Host: power-lines-message
    volumes:
      - ./PowerLinesAnalysisService:/home/dotnet/PowerLinesAnalysisService
      - ./PowerLinesAnalysisService.Tests:/home/dotnet/PowerLinesAnalysisService.Tests
      - ./scripts:/home/dotnet/scripts

  power-lines-message:
    image: rabbitmq:3-management-alpine
    container_name: power-lines-message
    hostname: power-lines-message
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitmq
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "15672:15672"
      - "5672:5672"

  power-lines-analysis-service-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: power_lines_analysis
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
