environment: production
name: power-lines-analysis-service
image: power-lines-analysis-service

container:
  requestMemory: 200Mi
  requestCpu: 120m
  limitMemory: 300Mi
  limitCpu: 120m
  port: 5003
  comPlusEnableDiagnostics: 0
  connectionString: "User Id=postgres;Password=postgres;Server=power-lines-analysis-service-postgres;Port=5432;Database=Database=power_lines_analysis;"

message:
  host: host.docker.internal
  port: 5672
  username: rabbitmq
  password: rabbitmq
  analysisQueue: power-lines-analysis
  resultQueue: power-lines-results
  resultSubscription: power-lines-results-analysis
  analysisSubscription: power-lines-analysis-analysis
  oddsQueue: power-lines-odds

deployment:
  minReplicas: 1
  maxReplicas: 5
  cpuThreshold: 80
  memoryThreshold: 80
  triggerQueueLength: 10
