environment: production
name: power-lines-analysis-service
image: power-lines-analysis-service

container:
  resourceTier: L
  port: 5003
  comPlusEnableDiagnostics: 0

message:
  host: services.lynxmagnus.com
  port: 5672
  analysisQueue: power-lines-analysis
  resultQueue: power-lines-results
  resultSubscription: power-lines-results-analysis
  analysisSubscription: power-lines-analysis-analysis
  oddsQueue: power-lines-odds

deployment:
  minReplicas: 1
  maxReplicas: 5
  cpuThreshold: 80
  memoryThreshold: 80
  triggerQueueLength: 10

secret:
  secretsPath: /power-lines-analysis-service
